---
- name: Home Assistant deployment
  hosts: all
  become: true

  tasks:
    - name: Update system packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install Home Assistant dependencies
      apt:
        name:
          - apparmor
          - cifs-utils
          - curl
          - dbus
          - jq
          - libglib2.0-bin
          - lsb-release
          - network-manager
          - nfs-common
          - systemd-journal-remote
          - systemd-resolved
          - udisks2
          - wget
        state: present

    - name: Install Docker CE
      shell: curl -fsSL get.docker.com | sh

    # - name: Add each host's user to the Docker group
    #   user:
    #     name: "{{ hostvars[inventory_hostname]['user'] }}"
    #     groups: docker
    #     append: yes
    #   # loop: "{{ groups['all'] }}"
    #   when: 'user' in hostvars[inventory_hostname]

    - name: Add each host's user to the Docker group
      user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: yes

    - name: Download latest OS Agent GitHub release (arm64)
      get_url:
        url: "https://github.com/home-assistant/os-agent/releases/latest/download/os-agent_{{ lookup('url', 'https://api.github.com/repos/home-assistant/os-agent/releases/latest', wantlist=True)[0].json.tag_name }}_linux_arm64.deb"
        dest: "/tmp/os-agent_latest_arm64.deb"

    - name: Install downloaded OS Agent package
      apt:
        deb: "/tmp/os-agent_latest_arm64.deb"

    - name: Remove tmp folder
      shell: rm -rf /tmp

    - name: Install Home Assistant Supervisor Debian package
      shell:
        cmd: |
          wget -O /tmp/homeassistant-supervised.deb https://github.com/home-assistant/supervised-installer/releases/latest/download/homeassistant-supervised.deb
          apt install /tmp/homeassistant-supervised.deb

- name: docker-compose deployment
  hosts: all
  become: true

  tasks:
    - name: Install docker-compose
      apt:
        name:
          - docker-compose
        state: present

    - name: Create server directory
      file:
        path: /home/server
        state: directory
        owner: "{{ ansible_user_id }}"
        group: docker
        mode: '0755'

    - name: Copy over docker-compose.yml
      copy:
        src: ../server/docker-compose.yml
        dest: /home/server/docker-compose.yml

    - name: Copy over .env file
      copy:
        src: ../server/.env
        dest: /home/server/.env
    
    - name: docker-compose up
      shell: docker-compose up -d
          
