- name: Home Assistant deployment
  hosts: all
  become: true

  tasks:
    - name: Update system packages
      ansible.builtin.apt:
        update_cache: true
        upgrade: true

    - name: Install Home Assistant dependencies
      ansible.builtin.apt:
        name:
          - apparmor
          - cifs-utils
          - curl
          - dbus
          - jq
          - libglib2.0-bin
          - lsb-release
          - network-manager
          - nfs-common
          - systemd-journal-remote
          - systemd-resolved
          - udisks2
          - wget
        state: present

    - name: Check if docker is installed
      ansible.builtin.command: docker --version
      register: docker_installed
      ignore_errors: true

    - name: Retrieve Docker install script
      ansible.builtin.get_url:
        url: https://get.docker.com
        dest: /tmp/get-docker.sh
        mode: "0755"
      when: docker_installed.failed

    - name: Install Docker CE
      ansible.builtin.shell:
        cmd: /tmp/get-docker.sh
        executable: /bin/bash
      register: result
      changed_when: "'Docker is already the newest version' not in result.stdout"
      when: docker_installed.failed

    - name: Add users to the Docker group
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: true

    - name: Install required Python libraries
      ansible.builtin.pip:
        name: github3.py
        extra_args: --user

    - name: Find current release tag for OS Agent
      community.general.github_release:
        user: home-assistant
        repo: os-agent
        action: latest_release
      register: release_data

    - name: Download latest OS Agent GitHub release (arm64)
      ansible.builtin.get_url:
        url: "https://github.com/home-assistant/os-agent/releases/latest/download/os-agent_{{ release_data.tag }}_linux_arm64.tar.gz"
        dest: "/tmp/os-agent_latest_arm64.tar.gz"
        mode: "0755"

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /tmp/os-agent_latest_arm64
        state: directory
        mode: "0755"

    - name: Extract tgz file
      ansible.builtin.unarchive:
        src: /tmp/os-agent_latest_arm64.tar.gz
        dest: /tmp/os-agent_latest_arm64/
        remote_src: true

    - name: Install downloaded OS Agent package
      ansible.builtin.shell:
        chdir: /tmp/os-agent_latest_arm64
        cmd: ./os-agent

    - name: Install Home Assistant Supervisor Debian package
      ansible.builtin.get_url:
        url: https://github.com/home-assistant/supervised-installer/releases/latest/download/homeassistant-supervised.deb
        dest: /tmp/homeassistant-supervised.deb
        
        mode: "0755"

    - name: Install .deb package
      ansible.builtin.apt:
        deb: /tmp/homeassistant-supervised.deb

    - name: Remove tmp folder
      ansible.builtin.file:
        path: /tmp
        state: absent
      changed_when: true
- name: Deploy docker-compose
  hosts: all
  become: true

  tasks:
    - name: Install docker-compose
      ansible.builtin.apt:
        name:
          - docker-compose
        state: present

    - name: Create server directory
      ansible.builtin.file:
        path: /home/server
        state: directory
        owner: "{{ ansible_user_id }}"
        group: docker
        mode: '0755'

    - name: Copy over docker-compose.yml
      ansible.builtin.copy:
        src: ../server/docker-compose.yml
        dest: /home/server/docker-compose.yml
        mode: '0644'

    - name: Copy over .env file
      ansible.builtin.copy:
        src: ../server/.env
        dest: /home/server/.env
        mode: '0644'

    - name: Run docker-compose
      ansible.builtin.shell: docker-compose up -d
      args:
        chdir: /home/server
      changed_when: true