- name: Home Assistant deployment
  hosts: all
  become: true

  tasks:
    - name: Update system packages
      ansible.builtin.apt:
        update_cache: true
        upgrade: true

    - name: Install Home Assistant dependencies
      ansible.builtin.apt:
        name:
          - apparmor
          - cifs-utils
          - curl
          - dbus
          - jq
          - libglib2.0-bin
          - lsb-release
          - network-manager
          - nfs-common
          - systemd-journal-remote
          - systemd-resolved
          - udisks2
          - wget
        state: present

    - name: Check if docker is installed
      ansible.builtin.command: docker --version
      register: docker_installed
      ignore_errors: true

    - name: Retrieve Docker install script
      ansible.builtin.get_url:
        url: https://get.docker.com
        dest: /tmp/get-docker.sh
        mode: "0755"
      when: docker_installed.failed

    - name: Install Docker CE
      ansible.builtin.shell:
        cmd: /tmp/get-docker.sh
        executable: /bin/bash
      register: result
      changed_when: "'Docker is already the newest version' not in result.stdout"
      when: docker_installed.failed

    - name: Add users to the Docker group
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: true


    - name: Download latest OS Agent GitHub release (arm64)
      ansible.builtin.get_url:
        url: "https://github.com/home-assistant/os-agent/releases/latest/download/os-agent_{{ lookup('url', 'https://api.github.com/repos/home-assistant/os-agent/releases/latest', wantlist=True)[0].json.tag_name }}_linux_arm64.deb"
        dest: "/tmp/os-agent_latest_arm64.deb"
        mode: '0644'

    - name: Install downloaded OS Agent package
      ansible.builtin.apt:
        deb: "/tmp/os-agent_latest_arm64.deb"

    - name: Remove tmp folder
      ansible.builtin.shell: rm -rf /tmp
      changed_when: true

    - name: Install Home Assistant Supervisor Debian package
      ansible.builtin.get_url:
        url: https://github.com/home-assistant/supervised-installer/releases/latest/download/homeassistant-supervised.deb
        dest: /tmp/homeassistant-supervised.deb
        
    - name: Install .deb package
      ansible.builtin.apt:
        deb: /tmp/homeassistant-supervised.deb

- name: Deploy docker-compose
  hosts: all
  become: true

  tasks:
    - name: Install docker-compose
      ansible.builtin.apt:
        name:
          - docker-compose
        state: present

    - name: Create server directory
      ansible.builtin.file:
        path: /home/server
        state: directory
        owner: "{{ ansible_user_id }}"
        group: docker
        mode: '0755'

    - name: Copy over docker-compose.yml
      ansible.builtin.copy:
        src: ../server/docker-compose.yml
        dest: /home/server/docker-compose.yml
        mode: '0644'

    - name: Copy over .env file
      ansible.builtin.copy:
        src: ../server/.env
        dest: /home/server/.env
        mode: '0644'

    - name: Run docker-compose
      ansible.builtin.shell: docker-compose up -d
      args:
        chdir: /home/server
      changed_when: true